- Sources/Select.swift
- Tests/SwiftKueryTests/TestJoin.swift
- Tests/SwiftKueryTests/TestSyntaxError.swift
Implemented a support for multiple join statements by introducing an array with required info such as `JOIN` type, `ON` clause (which could be a `Filter` or raw SQL) and `USING` clause.  
`.syntaxError` value is almost the same with exception that both `.on` and `.using` methods is checking `JOIN` clause existence when they are used and not on `.build`.
Also added tests to check if `Select` query with multiple joins is correct.
Issue: IBM-Swift/Swift-Kuery#29
> Multiple JOINS

- Sources/Delete.swift
- Sources/Filter.swift
- Sources/Having.swift
- Sources/Select.swift
- Sources/String+Buildable.swift
- Sources/Update.swift
I've added a `QueryFilterProtocol` and `QueryHavingProtocol` protocols, that is used in `Select` for `where`, `on` and `having` clauses and in `Update` for `where`.  
This removes possible errors where raw or Typed clause isn't used in `.build` method.
This also gives access for using different parameter types for `.where`, `.on` and `.having` methods in `Select` without implementing new methods.
> Simplify the use of clauses that use raw SQL.

- Sources/SwiftKuery/Delete.swift
- Sources/SwiftKuery/Insert.swift
- Sources/SwiftKuery/QuerySuffixProtocol.swift
- Sources/SwiftKuery/String+Buildable.swift
- Sources/SwiftKuery/Update.swift
- Tests/SwiftKueryTests/TestInsert.swift
- Tests/SwiftKueryTests/TestSyntaxError.swift
- Tests/SwiftKueryTests/TestUpdate.swift
Added a protocol for suffix clauses. This would simplify the use of `suffix` and would allow an extensions like `returning` method for PostgreSQL and other data bases that support it.
> Use protocol for suffix clauses

- Sources/SwiftKuery/Delete.swift
- Sources/SwiftKuery/Update.swift
- Sources/SwiftKuery/With.swift
- Tests/SwiftKueryTests/TestUpdate.swift
Removes `WITH` clauses for `UPDATE` and `DELETE`.
Fixes #52 
I'll implement an Extension points for `Query` type in next PR.
> Revert WITH clause for UPDATE, DELETE

- Sources/SwiftKuery/Delete.swift
- Sources/SwiftKuery/QueryBuilder.swift
- Sources/SwiftKuery/Update.swift
- Sources/SwiftKuery/With.swift
- Tests/SwiftKueryTests/CommonUtils.swift
- Tests/SwiftKueryTests/TestUpdate.swift
Implemented a temporary workaround for `UPDATE` and `DELETE` clauses for PostgreSQL which was discussed in #52.
Added a test cases to cover a workaround.
> WITH clause for UPDATE, DELETE

- Sources/SwiftKuery/Utils.swift
When queryBuilder.addNumbersToParameters is false, we still need to substitute occurrences of `Parameter.numberedParameterMarker` with the numberedParameter textual representation.
> Fix for when queryBuilder.addNumbersToParameters is false

- Sources/SwiftKuery/AggregateColumnExpression.swift
- Sources/SwiftKuery/AuxiliaryTable.swift
- Sources/SwiftKuery/Column.swift
- Sources/SwiftKuery/QueryBuilder.swift
- Sources/SwiftKuery/ScalarColumnExpression.swift
- Sources/SwiftKuery/Table.swift
- Sources/SwiftKuery/Utils.swift
MySQL uses backquotes instead of double quotes to quote identifiers with spaces or special characters. This change makes this character customizable using QuerySubstitutionNames keeping the default the same as it currently is hardcoded to (double quotes).
> Make identifier quote character for packName() customizable

- Sources/SwiftKuery/ConnectionPool.swift
As we already locked/decremented `poolLock` in line 121, calling `lockPoolLock()` again by calling `give(_ item: Connection)` always deadlocks. So we need to either change `poolLock` to a re-entrant lock like `NSRecursiveLock` or do the change in this PR.
> Avoid poolLock.wait deadlock

- Sources/SwiftKuery/Table.swift
Adding a table init for the creation of tables is the ORM
> feat: add new init to table.swift

- Sources/SwiftKuery/Predicate.swift
I have already signed the CLA.
This fixes a bug where dates were not correctly formatted in certain queries, as the query builder was not used.
> Fixed not using provided date formatter

- Sources/SwiftKuery/ConnectionPool.swift
In case no connection can be established to the database we need to
make sure to signal the connection pool semaphore when retuning nil in
take(), otherwise libdispatch will complain (and crash the application)
when deallocating the connection pool (including the semaphore).
> Fix crash when deallocating connection pool

- Sources/SwiftKuery/ForeignKey.swift
- Sources/SwiftKuery/Table.swift
- Tests/SwiftKueryTests/TestSchema.swift
This PR improves Swift-Kuery's support for foreign keys.
With the changes it is now possible to specify multiple foreign keys on a table.
It should be noted that a user will still need to ensure their tables are built correctly to allow the use of composite keys.
> Improve foreign key support

- Package.swift
- Sources/SwiftKuery/ConnectionPool.swift
Follows on from #128 and #103.
When the ConnectionPool is first created but the database is unreachable, it can fail to generate connections (if the generator has been written in such a way that only 'good' connections are returned).
In this scenario, the pool's current `capacity` (the initial number of connections we try to generate) is out of sync with the actual size of the pool (represented by `pool.count`), which is normally only the case when connections have been vended from the pool and not yet returned.  We cannot recover from this situation, as we will not attempt to grow the pool, as its capacity is (apparently) not zero.
This fix ensures that the initial capacity and pool.count are in sync immediately after connection generation.  We will attempt to generate a new connection …
> Handle failure of ConnectionPool connection generator

- Sources/SwiftKuery/Column.swift
- Sources/SwiftKuery/QueryBuilder.swift
- Tests/SwiftKueryTests/CommonUtils.swift
- Tests/SwiftKueryTests/TestSchema.swift
Update createAutoIncrement signature to accept a Boolean denoting primary key status
> Add AUTO INCREMENT support for SQLite

- Sources/SwiftKuery/Column.swift
- Sources/SwiftKuery/Insert.swift
- Sources/SwiftKuery/RawField.swift
- Sources/SwiftKuery/Select.swift
- Sources/SwiftKuery/Utils.swift
- Tests/SwiftKueryTests/TestAggregateFunctions.swift
- Tests/SwiftKueryTests/TestAlias.swift
- Tests/SwiftKueryTests/TestFilterAndHaving.swift
- Tests/SwiftKueryTests/TestInsert.swift
- Tests/SwiftKueryTests/TestJoin.swift
- Tests/SwiftKueryTests/TestParameters.swift
- Tests/SwiftKueryTests/TestRaw.swift
- Tests/SwiftKueryTests/TestSchema.swift
- Tests/SwiftKueryTests/TestSelect.swift
- Tests/SwiftKueryTests/TestSpecialOperators.swift
- Tests/SwiftKueryTests/TestSubqueries.swift
- Tests/SwiftKueryTests/TestSubquery.swift
- Tests/SwiftKueryTests/TestUpdate.swift
Add case protection for names.
- Updated SwiftKuery tests to check all identifiers are wrapped in "'s. (apart from raw strings)
- Updated build functions to wrap identifiers when building SQL statements.
Mixed case column names now work consistently across postgreSQL, mySQL and SQLite.
> Add case protection for postgreSQL

- Sources/SwiftKuery/Column.swift
- Tests/SwiftKueryTests/TestAggregateFunctions.swift
- Tests/SwiftKueryTests/TestAlias.swift
- Tests/SwiftKueryTests/TestFilterAndHaving.swift
- Tests/SwiftKueryTests/TestInsert.swift
- Tests/SwiftKueryTests/TestJoin.swift
- Tests/SwiftKueryTests/TestParameters.swift
- Tests/SwiftKueryTests/TestSelect.swift
- Tests/SwiftKueryTests/TestSpecialOperators.swift
- Tests/SwiftKueryTests/TestSubqueries.swift
- Tests/SwiftKueryTests/TestSubquery.swift
- Tests/SwiftKueryTests/TestUpdate.swift
Update the build method of Column to always pack the table name and column name seperately, eg, "myTable"."myColumn".
> Ensure column names are packed correctly

- Sources/SwiftKuery/QueryBuilder.swift
- Sources/SwiftKuery/ScalarColumnExpression.swift
The `MID` function is a synonym for `SUBSTRING` on PostgreSQL and MySQL, but on SQLite, no synonym exists for its equivalent `SUBSTR` function. We need to do a substitution for it, but we can't since it's not currently substitutable. This PR resolves that; once in place, we'll be able to put the substitution in place in Swift-Kuery-SQLite.
> Make the MID function substitutable by Kuery implementations

- Sources/SwiftKuery/ConnectionPool.swift
When the Connection pool is initialised the `pool.count`, `capacity` and `semaphore` should all be in sync. 
In the current implementation we set the `semaphore` to the `capacity` size, but then we compare the `pool.count` size to the `capacity` size and if `pool.count` is less than `capacity` we make `capacity` equal to `pool.count`. Doing this would then bring the `semaphore` out of sync. 
With this change, we will now set the `semaphore` using the `pool.count` value and we only set this after we've finished calculating the `pool.count` value so it can't change during the initialisation.
> Set semaphore in correct location

- README.md
In the section of the README depicting how to import the package as a dependency, it tells the user to find the latest version of swift-kuery-postgresql from https://github.com/IBM-Swift/Swift-Kuery/releases when it should point them towards https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL/releases
> Fix broken releases link in README.md

- Sources/SwiftKuery/Table.swift
- Tests/SwiftKueryTests/TestSchema.swift
Mirroring the children and extracting the table name and columns is pretty slick. But, with this, it's not possible to reuse the same table elsewhere with a different name.
Also, since `Column` stores a `weak var` of the associated table, we can't do this either:
```swift
let table1 = SomeTable()
let table2 = SomeTable(tableName: "new name", columns: table1.columns)
```
... since that will change the columns of `table1` to point to `table2`. So, I've added an optional parameter to the `Table` initializer.
> Support overriding table names during initialization

- Sources/SwiftKuery/Column.swift
This includes the `checkExpression` and `autoIncrement` values while creating a new copy of the column.
> Properly initalize Column while aliasing

- Sources/SwiftKuery/Column.swift
- Sources/SwiftKuery/ColumnCreator.swift
- Sources/SwiftKuery/ConnectionPoolConnection.swift
- Sources/SwiftKuery/QueryBuilder.swift
- Tests/SwiftKueryTests/CommonUtils.swift
- Tests/SwiftKueryTests/TestSchema.swift
This PR updates query to offload the building of column descriptions the an underlying DB plugin. This has the advantage of being able to handle plugin specific behaviors without conditional logic in base Kuery.
> Build Column descriptions in the plugins

- .travis.yml
- Sources/SwiftKuery/ColumnAndExpressions_Extensions.swift
- Sources/SwiftKuery/ConditionalClause.swift
- Sources/SwiftKuery/Field.swift
- Sources/SwiftKuery/FilterAndHaving_Extensions.swift
- Sources/SwiftKuery/Query.swift
- Sources/SwiftKuery/ResultSet.swift
- Sources/SwiftKuery/ScalarColumnExpression.swift
- Sources/SwiftKuery/SpecialOperators_Extensions.swift
- Sources/SwiftKuery/Subqueries_GlobalFunctionsAndExtensions.swift
Adds testing with a Swift 5 development snapshot. The snapshot is defined in Travis as `SWIFT_DEVELOPMENT_SNAPSHOT` consistently across the IBM-Swift repos, to enable us to automate updating the version.
Resolves a number of Swift 5 compilation warnings:
- removal of redundant `public` default modifier on extensions (whose members are all explicitly declared public),
- removal of a redundant `internal (set)` declaration on an internal property,
- removal of an empty associated value on an enum.
> Build against Swift 5

- Sources/SwiftKuery/QueryResult.swift
This PR updates `QueryResult.asRows` to ensure an embedded `resultSet` is closed when an error occurs.
The PR also updates `QueryResult.processRows` for the same reason.
> Ensure result set is released when error occurs during asRows

- Sources/SwiftKuery/Column.swift
- Sources/SwiftKuery/ColumnCreator.swift
- Tests/SwiftKueryTests/CommonUtils.swift
- Tests/SwiftKueryTests/TestInsert.swift
- Tests/SwiftKueryTests/TestSchema.swift
- Tests/SwiftKueryTests/TestUpdate.swift
This PR adds support for using nil to represent NULL for default column values.
The PR also adds test for inset, update and table creation when using nil values.
> Enhance support for nil values

- README.md
This pull request updates the usage example to explicitly import Swift-Kuery. This is because if you rely on the plugin and the plugin changes to a new major of Swift-Kuery you application could break since you interact with Swift-Kuery directly.
> Update useage example in README.md
